#https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=tasks-creating-operator-subscriptions#preinstall-operator-subscriptions__cpd-subscription

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-db2wh-cp4d-operator-catalog-subscription
  namespace: {{ .Values.operator_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5" 
spec:
  channel: {{ .Values.db2wh_channel }}
  name: ibm-db2wh-cp4d-operator
  installPlanApproval: Automatic
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace

# Need to find why they have 2 subscriptions