apiVersion: v1
kind: ConfigMap
metadata:
  name: db2-kernel-config-script
  namespace: {{ .Values.cpd_namespace }}
  labels:
    app: cp-db2-kernel
data:
  cp_db2_kernel_setup.sh: |
    #!/bin/sh

    oc patch deployment ibm-db2wh-cp4d-operator-controller-manager --patch '{"spec": {"replicas": 0}}' -n "${OperatorNamespace}"
    oc get cm db2u-json-cm -n="${InstanceNamespace}" -o=json | sed 's/set-kernel-params\\\": false/set-kernel-params\\\": true/g' | oc apply -f-
    oc delete po $(oc get po -n="${InstanceNamespace}" | grep zen-database-core | awk {'print $1'}) -n="${InstanceNamespace}"
    sleep 30s
  cp_db2_finalize_kernel_setup.sh: |
    #!/bin/sh

    oc patch deployment ibm-db2wh-cp4d-operator-controller-manager --patch '{"spec": {"replicas": 1}}' -n "${OperatorNamespace}"
    sleep 30s