apiVersion: databases.cpd.ibm.com/v1
kind: Db2whService
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.gitops-cp4d-instance }}
  annotations:
    argocd.argoproj.io/sync-wave: "1" 
spec:
  license:
    accept: true
    license: Enterprise
  db_type: {{ .Values.db_type }}