apiVersion: databases.cpd.ibm.com/v1
kind: Db2whService
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.cpd_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1" 
spec:
  license:
    accept: {{ .Values.license_accept }}
    license: {{ .Values.license }}
  db_type: db2wh