apiVersion: databases.cpd.ibm.com/v1
kind: Db2whService
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.cpd_namespace }} 
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  license:
    accept: true
    license: Enterprise
  db_type: db2wh