
apiVersion: databases.cpd.ibm.com/v1
kind: Db2whService
metadata:
  name: db2wh-cr
  namespace: {{ .Values.cpd_operators }}
spec:
  license:
    accept: {{ .Values.license_accept }}
    license: {{ .Values.license }}
